"""Generate WeatherSans 1-bit glyph subsets from OFL-licensed Noto Sans SC.

Usage: python tools/generate_weather_fonts.py --font path/to/NotoSansSC.ttf
Requires Pillow. Add custom place characters to main/fonts/characters.txt first.
"""
import argparse
from pathlib import Path
from PIL import Image, ImageDraw, ImageFont

ROOT = Path(__file__).resolve().parents[1]


def generate(font_path, size, characters):
    font = ImageFont.truetype(str(font_path), size)
    font.set_variation_by_name("SemiBold")
    bounds = {c: font.getbbox(c, anchor="ls") for c in characters}
    top = min(box[1] for box in bounds.values())
    bottom = max(box[3] for box in bounds.values())
    bitmap = bytearray()
    records = []
    for character in sorted(characters, key=ord):
        left, ytop, right, ybottom = bounds[character]
        width, height = right - left, ybottom - ytop
        offset = len(bitmap)
        image = Image.new("L", (max(width, 1), max(height, 1)))
        ImageDraw.Draw(image).text((-left, -ytop), character, font=font, fill=255, anchor="ls")
        packed = bytearray((width * height + 7) // 8)
        samples = list(image.tobytes()) if width and height else []
        for bit, gray in enumerate(samples):
            if gray >= 100:
                packed[bit // 8] |= 0x80 >> (bit % 8)
        bitmap.extend(packed)
        records.append(f"    {{0x{ord(character):x}, {offset}, {width}, {height}, "
                       f"{round(font.getlength(character))}, {left}, {ytop - top}}},")
    name = f"WeatherSans{size}"
    rows = [", ".join(f"0x{b:02x}" for b in bitmap[i:i + 20]) for i in range(0, len(bitmap), 20)]
    source = f"static const uint8_t bitmap{size}[] = {{\n    " + ",\n    ".join(rows) + "\n};\n"
    source += f"static const UiGlyph glyphs{size}[] = {{\n" + "\n".join(records) + "\n};\n"
    source += f"const UiFont {name} = {{glyphs{size}, bitmap{size}, {len(records)}, {bottom - top}}};\n"
    print(f"{name}: {len(records)} glyphs, height {bottom - top}, bitmap {len(bitmap)} bytes")
    return source


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--font", type=Path, required=True)
    args = parser.parse_args()
    characters = set(chr(i) for i in range(32, 127)) | set("℃°…?")
    sources = ["main/weather_ui.c", "components/weather/src/weather_parse.c",
               "components/weather/Kconfig.projbuild", "main/fonts/characters.txt"]
    for filename in sources:
        characters.update(c for c in (ROOT / filename).read_text(encoding="utf-8") if ord(c) > 127 and not c.isspace())
    header = "// Generated by tools/generate_weather_fonts.py; source font license: OFL.txt.\n#pragma once\n#include \"color_canvas.h\"\n"
    source = "// WeatherSans bitmap subset derived from Noto Sans SC under SIL OFL 1.1.\n// Generated file. See OFL.txt and tools/generate_weather_fonts.py.\n#include \"weather_font.h\"\n\n"
    for size in (10, 13, 16, 20, 32, 44):
        subset = characters if size <= 20 else set("0123456789.-?")
        source += generate(args.font, size, subset) + "\n"
        header += f"extern const UiFont WeatherSans{size};\n"
    (ROOT / "main/fonts/weather_font.h").write_text(header, encoding="utf-8")
    (ROOT / "main/fonts/weather_font.c").write_text(source.rstrip() + "\n", encoding="utf-8")


if __name__ == "__main__":
    main()
