// Generated by tools/generate_weather_fonts.py; source font license: OFL.txt.
#pragma once
#include "color_canvas.h"
extern const UiFont WeatherSans10;
extern const UiFont WeatherSans13;
extern const UiFont WeatherSans16;
extern const UiFont WeatherSans20;
extern const UiFont WeatherSans32;
extern const UiFont WeatherSans44;
